### PR TITLE
Add version number

### PR DESCRIPTION
**Pull request by Synicix**
image

### CODE REVIEW

**Review by guzman-raphael — CHANGES_REQUESTED** [review]
@Synicix A few points from this:
- Let's add the backend version as well.
- I would source the version from `package.json` to keep the version spec in one place.

**Review by guzman-raphael — APPROVED** [review]
@Synicix Changes look good, would you update the screen shot in the body to reflect the final one?

**Comment by Synicix** [comment]
image

**Comment by Synicix** [comment]
Move location of versions

**Review by guzman-raphael — APPROVED** [review]

**Pull request merged**
